name: UnsafeEnchant
main: fr.jules_cesar.UnsafeEnchant.UnsafeEnchant
version: 1.1
author: Jules_Cesar
depend: [Vault]
commands:
    enchantu:
        description: Objet fou !
    damage:
        description: Casse ton objet !
permissions:
    UnsafeEnchant.use:
      default: false
