name: UnsafeEnchant
main: fr.jules_cesar.UnsafeEnchant.UnsafeEnchant
version: 1.2
author: Jules_Cesar
depend: [Vault]
commands:
    enchantu:
        description: Objet fou !
permissions:
    UnsafeEnchant.use:
      default: false
